services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    volumes:
      - ./public/uploads:/remixapp/public/uploads
      - ./sessions:/remixapp/sessions
      - ./app/utils:/app/utils
      - ./app/database:/app/database
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "npm run email-worker & npm run start"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
  
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle:/data
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    ports:
      - "${DOZZLE_PORT}:8080"

volumes:
  postgres_data:
  redis_data: 