services:
  app:
    build:
      target: production
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./certs:/remixapp/certs
      - ./public:/remixapp/public
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm run email-worker & npm run start"