services:
  app:
    build:
      target: deps
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/remixapp
      - /remixapp/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm run email-worker & npm run dev" 