version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - HOST=0.0.0.0
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=ecommerce_db
      - PG_USERNAME=ecommerce_user
      - PG_PASSWORD=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=your-secret-key
    volumes:
      - ./public/uploads:/remixapp/public/uploads
      - ./sessions:/remixapp/sessions
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 